[package]
name = "tmfast"
version = "0.1.0"
authors = ["Cassaundra <cass@cassaundra.io>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
directories = "2.0.1"
petgraph = "0.4.13"
serde = "1.0.94"
serde_json = "1.0.40"
termion = "1.5.3"
tokio = "0.1.22"